BILINEAR_FORM = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
]

BASIS = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
]

INITIAL_POINT = [0, 0, 0]
CAMERA_DIRECTION = [1, 0, 0]

FIELD_OF_VIEW = 2
DRAW_DISTANCE = 100
SCREEN_HEIGHT = 200
SCREEN_WIDTH = 200
