INITIAL_POINT = [-10, 0, 2]
ROTATION_HALF_PI_DISCRETIZATION = 4
HORIZONTAL_FIELD_OF_VIEW_OUT_OF_PI = 0.5
VERTICAL_FIELD_OF_VIEW_OUT_OF_PI = 0.28
DRAW_DISTANCE = 10
PRECISION = 100
CHARMAP = "$@&%#WMNB8RGAHP694XKYJOUVIL*+:-."
