INITIAL_POINT = [-10, 0, 4]
ROTATION_HALF_PI_DISCRETIZATION = 6
HORIZONTAL_FIELD_OF_VIEW_OUT_OF_PI = 0.666666
VERTICAL_FIELD_OF_VIEW_OUT_OF_PI = 0.5
DRAW_DISTANCE = 100
PRECISION = 100
CHARMAP = "$@&%#WMNB8RGAHP694XKYJOUVIL*+:-."
